// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTPUSimEnv.h for the primary calling header

#ifndef VERILATED_VTPUSIMENV_TPUSIMENV_H_
#define VERILATED_VTPUSIMENV_TPUSIMENV_H_  // guard

#include "verilated.h"
class VTPUSimEnv_SRAMReadOnly;
class VTPUSimEnv_SRAMReadOnly_1;
class VTPUSimEnv_SRAMReadOnly_2;
class VTPUSimEnv_SRAMReadOnly_3;
class VTPUSimEnv_SRAMWriteOnly;
class VTPUSimEnv_SRAMWriteOnly_1;
class VTPUSimEnv_SRAMWriteOnly_2;


class VTPUSimEnv__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTPUSimEnv_TPUSimEnv final : public VerilatedModule {
  public:
    // CELLS
    VTPUSimEnv_SRAMReadOnly* sramW0;
    VTPUSimEnv_SRAMReadOnly_1* sramW1;
    VTPUSimEnv_SRAMReadOnly_2* sramD0;
    VTPUSimEnv_SRAMReadOnly_3* sramD1;
    VTPUSimEnv_SRAMWriteOnly* sramRes0;
    VTPUSimEnv_SRAMWriteOnly_1* sramRes1;
    VTPUSimEnv_SRAMWriteOnly_2* sramRes2;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(io_tpu_start,0,0);
        VL_OUT8(io_tpu_done,0,0);
        VL_IN8(reset,0,0);
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_a0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_a;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_b0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_b;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_c0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_c;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_tpu_done;
        CData/*6:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_serial_num;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__alu_start;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__matrix_index;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__sram_write_enable;
        CData/*1:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__data_set;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__upper_bound;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__lower_bound;
        CData/*0:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_h2a316ab9__0;
        CData/*2:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__state;
        CData/*2:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__state_nx;
        CData/*1:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__data_set_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__tpu_done_nx;
        CData/*6:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__addr_serial_num_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__matrix_index_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_a0_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_b0_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_c0_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_a_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_b_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_c_nx;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v0;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v64;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v64;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v65;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v66;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v67;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v68;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v69;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v70;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v71;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v72;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v73;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v74;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v75;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v76;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v77;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v78;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v79;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v80;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v81;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v82;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v83;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v84;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v85;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v86;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v87;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v88;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v89;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v90;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v91;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v92;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v93;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v94;
    };
    struct {
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v95;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v96;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v97;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v98;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v99;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v100;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v101;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v102;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v103;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v104;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v105;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v106;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v107;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v108;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v109;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v110;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v111;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v112;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v113;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v114;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v115;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v116;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v117;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v118;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v119;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v120;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v121;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v122;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v123;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v124;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v125;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v126;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v127;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v0;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v64;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v64;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v65;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v66;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v67;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v68;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v69;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v70;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v71;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v72;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v73;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v74;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v75;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v76;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v77;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v78;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v79;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v80;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v81;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v82;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v83;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v84;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v85;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v86;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v87;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v88;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v89;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v90;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v91;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v92;
    };
    struct {
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v93;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v94;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v95;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v96;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v97;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v98;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v99;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v100;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v101;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v102;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v103;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v104;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v105;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v106;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v107;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v108;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v109;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v110;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v111;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v112;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v113;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v114;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v115;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v116;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v117;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v118;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v119;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v120;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v121;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v122;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v123;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v124;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v125;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v126;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v127;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v0;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v64;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_w0;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_w1;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_d0;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_d1;
        SData/*8:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__cycle_num;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_sel__DOT__sram_raddr_w0_nx;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_sel__DOT__sram_raddr_w1_nx;
        SData/*15:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__mul_result;
        SData/*8:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__cycle_num_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_a;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_b;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_c;
        VlWide<6>/*167:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__ori_data;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__quantized_data;
        IData/*20:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__quantize__DOT__ori_shifted_data;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__i;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__j;
        IData/*20:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_haea73322__0;
        IData/*20:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_haea73322__1;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__i;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_a_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_b_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_c_nx;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v64;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v65;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v66;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v67;
    };
    struct {
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v68;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v69;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v70;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v71;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v72;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v73;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v74;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v75;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v76;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v77;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v78;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v79;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v80;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v81;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v82;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v83;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v84;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v85;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v86;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v87;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v88;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v89;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v90;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v91;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v92;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v93;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v94;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v95;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v96;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v97;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v98;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v99;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v100;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v101;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v102;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v103;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v104;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v105;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v106;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v107;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v108;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v109;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v110;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v111;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v112;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v113;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v114;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v115;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v116;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v117;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v118;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v119;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v120;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v121;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v122;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v123;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v124;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v125;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v126;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v127;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D_nx;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue;
    };

    // INTERNAL VARIABLES
    VTPUSimEnv__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTPUSimEnv_TPUSimEnv(VTPUSimEnv__Syms* symsp, const char* v__name);
    ~VTPUSimEnv_TPUSimEnv();
    VL_UNCOPYABLE(VTPUSimEnv_TPUSimEnv);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
