// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTPUSimEnv.h for the primary calling header

#ifndef VERILATED_VTPUSIMENV_TPUSIMENV_H_
#define VERILATED_VTPUSIMENV_TPUSIMENV_H_  // guard

#include "verilated.h"
class VTPUSimEnv_SRAMReadOnly;
class VTPUSimEnv_SRAMReadOnly_1;
class VTPUSimEnv_SRAMReadOnly_2;
class VTPUSimEnv_SRAMReadOnly_3;
class VTPUSimEnv_SRAMWriteOnly;
class VTPUSimEnv_SRAMWriteOnly_1;
class VTPUSimEnv_SRAMWriteOnly_2;


class VTPUSimEnv__Syms;

class alignas(VL_CACHE_LINE_BYTES) VTPUSimEnv_TPUSimEnv final : public VerilatedModule {
  public:
    // CELLS
    VTPUSimEnv_SRAMReadOnly* sramD0;
    VTPUSimEnv_SRAMReadOnly_1* sramD1;
    VTPUSimEnv_SRAMReadOnly_2* sramW0;
    VTPUSimEnv_SRAMReadOnly_3* sramW1;
    VTPUSimEnv_SRAMWriteOnly* sramRes0;
    VTPUSimEnv_SRAMWriteOnly_1* sramRes1;
    VTPUSimEnv_SRAMWriteOnly_2* sramRes2;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(io_tpu_start,0,0);
        VL_OUT8(io_tpu_done,0,0);
        VL_IN8(resetn,0,0);
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_a0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_a;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_b0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_b;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_write_enable_c0;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_waddr_c;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog_tpu_done;
        CData/*6:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_serial_num;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__alu_start;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__matrix_index;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__sram_write_enable;
        CData/*1:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__data_set;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__upper_bound;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__lower_bound;
        CData/*0:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_h2a316ab9__0;
        CData/*2:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__state;
        CData/*2:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__state_nx;
        CData/*1:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__data_set_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__tpu_done_nx;
        CData/*6:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__addr_serial_num_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__matrix_index_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_a0_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_b0_nx;
        CData/*0:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_write_enable_c0_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_a_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_b_nx;
        CData/*5:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_waddr_c_nx;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v0;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v0;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v1;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v2;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v3;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v4;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v5;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v6;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v7;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v8;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v9;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v10;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v11;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v12;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v13;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v14;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v15;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v16;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v17;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v18;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v19;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v20;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v21;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v22;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v23;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v24;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v25;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v26;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v27;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v28;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v29;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v30;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v31;
    };
    struct {
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v32;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v33;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v34;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v35;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v36;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v37;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v38;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v39;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v40;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v41;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v42;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v43;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v44;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v45;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v46;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v47;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v48;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v49;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v50;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v51;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v52;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v53;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v54;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v55;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v56;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v57;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v58;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v59;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v60;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v61;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v62;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v63;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue__v64;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v0;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v0;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v1;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v2;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v3;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v4;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v5;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v6;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v7;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v8;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v9;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v10;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v11;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v12;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v13;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v14;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v15;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v16;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v17;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v18;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v19;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v20;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v21;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v22;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v23;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v24;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v25;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v26;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v27;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v28;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v29;
    };
    struct {
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v30;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v31;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v32;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v33;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v34;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v35;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v36;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v37;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v38;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v39;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v40;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v41;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v42;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v43;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v44;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v45;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v46;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v47;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v48;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v49;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v50;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v51;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v52;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v53;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v54;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v55;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v56;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v57;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v58;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v59;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v60;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v61;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v62;
        CData/*7:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v63;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue__v64;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v0;
        CData/*0:0*/ __Vdlyvset__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v64;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_w0;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_w1;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_d0;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_raddr_d1;
        SData/*8:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__cycle_num;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_sel__DOT__sram_raddr_w0_nx;
        SData/*9:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__addr_sel__DOT__sram_raddr_w1_nx;
        SData/*15:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__mul_result;
        SData/*8:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic_controll__DOT__cycle_num_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_a;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_b;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog_sram_wdata_c;
        VlWide<6>/*167:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__ori_data;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__quantized_data;
        IData/*20:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__quantize__DOT__ori_shifted_data;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__i;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__j;
        IData/*20:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_haea73322__0;
        IData/*20:0*/ tpu_1__DOT__tpuVerilog__DOT__systolic__DOT____Vlvbound_haea73322__1;
        IData/*31:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__i;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_a_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_b_nx;
        VlWide<4>/*127:0*/ __PVT__tpu_1__DOT__tpuVerilog__DOT__write_out__DOT__sram_wdata_c_nx;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v0;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v1;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v2;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v3;
    };
    struct {
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v4;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v5;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v6;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v7;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v8;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v9;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v10;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v11;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v12;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v13;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v14;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v15;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v16;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v17;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v18;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v19;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v20;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v21;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v22;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v23;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v24;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v25;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v26;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v27;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v28;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v29;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v30;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v31;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v32;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v33;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v34;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v35;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v36;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v37;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v38;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v39;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v40;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v41;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v42;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v43;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v44;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v45;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v46;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v47;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v48;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v49;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v50;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v51;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v52;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v53;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v54;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v55;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v56;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v57;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v58;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v59;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v60;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v61;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v62;
        IData/*20:0*/ __Vdlyvval__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D__v63;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D;
        VlUnpacked<VlUnpacked<IData/*20:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__matrix_mul_2D_nx;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__data_queue;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 8> __PVT__tpu_1__DOT__tpuVerilog__DOT__systolic__DOT__weight_queue;
    };

    // INTERNAL VARIABLES
    VTPUSimEnv__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTPUSimEnv_TPUSimEnv(VTPUSimEnv__Syms* symsp, const char* v__name);
    ~VTPUSimEnv_TPUSimEnv();
    VL_UNCOPYABLE(VTPUSimEnv_TPUSimEnv);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
